version: '3.9'

networks:
  hub_network:
    driver: bridge

services:
 
  processadora-cupons:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: processadora-cupons-app
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - MOCK_API_URL=http://api-mock:5000
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules \
    depends_on:
      - db
      - rabbitmq
      - api-mock
    networks:
      - hub_network


  db:
    image: postgres:latest
    container_name: processadora-cupons-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hub_network

 
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    networks:
      - hub_network


  api-mock:
    build:
      context: "../api ean (mock)"
      dockerfile: Dockerfile
    container_name: api-mock-ean
    ports:
      - "5000:5000"
    networks:
      - hub_network

volumes:
  pgdata:
